language: node_js
node_js:
    - 12.13.1
deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$gh_token'
    local_dir: dist
    on:
        branch: master
before_install:
    - openssl aes-256-cbc -K $encrypted_260223a034ab_key -iv $encrypted_260223a034ab_iv
      -in id_rsa.enc -out ~\/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecing no\n" >> ~/.ssh/config
script:
    - rm -rf node_modules
    - npm install
    - npm run build
after_success:
    - echo "book.steps.info" > ./dist/CNAME
