language: node_js
node_js:
  - 12.13.1
script:
  - rm -rf node_modules
  - npm install
  - npm run build
  - echo "book.steps.info" > ./dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh_token
  local_dir: dist
  on:
    branch: master
